project:
  type: book
book:
  title: "JDemetra+ documentation"
  
  reader-mode: false
  sharing: [facebook, twitter, linkedin]
  
  page-footer:
    right: |
      <li><a href="https://github.com/annasmyk/JD_Quarto_Book" target="blank">Code source</a></li>
    left: |
      This book was built with <a href="https://quarto.org/">Quarto</a>.
  
  repo-actions: [edit,issue]
  site-url: https://jdemetra-new-documentation.netlify.app/
  repo-url: https://github.com/annasmyk/JD_Quarto_Book
  repo-branch: main
  # cover-image: resources/logo-utilitr.png
  # favicon: resources/logo-utilitr.png
  
  sidebar:
    style: "floating"
    search: true
    collapse-level: 1
    
  author:
    - name: Anna Smyk (Coordinator)
      url: https://github.com/annasmyk
      affiliations:
        - name: Insee
          country: France
          city: Paris
          url: "https://www.insee.fr/fr/accueil"
    - name: Tanguy Barthelemy
      url: https://github.com/TanguyBarthelemy
      affiliations:
        - name: Insee
          country: France
          city: Paris
          url: "https://www.insee.fr/fr/accueil"
      role: "Author"
    - name: Karsten Webel
      url: https://github.com/webelk
      affiliations:
        - name: Deutsche Bundesbank
          country: Germany
          city: Frankfurt
          url: "https://www.bundesbank.de"
      role: "Collaborator"
    - name: Maria Novas Filgueira
      url: https://github.com/maria-novas
      affiliations:
        - name: Ine
          country: Spain
          city: Madrid
          url: "https://www.ine.es/"
      role: "Collaborator"
    - name: Luis Sanguiao Sande
      affiliations:
        - name: Ine
          country: Spain
          city: Madrid
          url: "https://www.ine.es/"
      role: "Collaborator"
    - name: Felix Aparicio Perez
      affiliations:
        - name: Ine
          country: Spain
          city: Madrid
          url: "https://www.ine.es/"
      role: "Collaborator"
  date: "03/31/2025"
  page-navigation: true
  chapters:
    - index.qmd
    ##- example.qmd
    - G-how-to-use-this-book.qmd ## (#G-use-book)
    - G-news-v3-vs-v2.qmd ##(#v3-vs-v2)
    ##- G-jd-history.qmd ##(#g-jd-hist)
    - part: P_Algorithms.qmd ##(#part-A)
      chapters:
        - A-RegArima-Tramo-Modelling-Overview.qmd ## (#a-reg-a)
        - A-sa-overview.qmd ##(#sa-overview)
        - A-sa-pre-treatment.qmd ##(#sa-pre-t)
        - A-sa-X11-decomposition.qmd ##(a-sa-X11)
        - A-sa-seats-decomposition.qmd ##(#a-sa-seats)
        - A-rev-policies.qmd ##(#a-rev-pol)
        - A-sa-hf.qmd ##(#a-sa-hf)
        - A-sa-x12.qmd
        - A-sa-stl-decomposition.qmd ##(#a-sa-stl)
        - A-sa-bsm.qmd ##(#a-sa-bsm)
        - A-outlier-detection.qmd ##(#a-out-reg-ext)
        - A-calendar-correction.qmd ##(#a-cal)
        - A-benchmarking.qmd ##(#a-bench)
        - A-trend-cycle-estimation.qmd ##(#a-trend)
        - A-revision-analysis.qmd ##(#a-revs)
        - A-nowcasting.qmd ##(#a-now)
    - part: P_Tools.qmd ##(#part-T)
      chapters:
        - T-GUI-Overview.qmd ##(#t-gui-overview)
        - T-GUI-Data-Viz-TS-Tools.qmd ##(#t-GUI-tstools)
        - T-GUI-SA-Modelling-Features.qmd ##(#t-gui-sa)
        - T-GUI-Output.qmd ##(#t-gui-output)
        - T-plug-ins.qmd ##(#t-plug-ins)
        - T-Production-tools-cruncher-QR.qmd ##(#t-prod)
        - T-r-packages.qmd ##(#t-r-packs)
    - part: P_Methods.qmd ##(#part-T)
      chapters:
        - M-spectral-analysis.qmd ##(#m-spectrum)
        - M-reg-arima-modelling.qmd ##(#m-reg-a)
        - M-X11-decomposition.qmd ##(#m-X11)
        - M-SEATS-decomposition.qmd ##(#m-seats)
        #- M-sa-hf.qmd ##(#m-sa-hf)
        # - M-Trend-Estimation-Local-Polynomials.qmd ##(#m-trend)
        - M-tests.qmd ##(#m-tests)
        - M-STL-decomposition.qmd ##(#m-stl)
        # - M-state-space-framework.qmd ##(#m-ssf)
        - M-Temp-Disagg-Bench.qmd ##(#m-bench)
        - M-revision-analysis.qmd ##(#m-revs)
    - Output_Description.qmd ##(#output-chap)
    - references.qmd
bibliography: references.bib

format:
  html:
    grid:
      body-width: 800px
    theme: 
        - united
        - custom.scss
    css: styles.css
  pdf:
    mainfont: "DejaVu Sans"
    documentclass: scrreprt

editor: source
